# The Conventional Commits toolbox
# see: https://github.com/cocogitto/cocogitto

# All version numbers should be prefixed with v to denote
# a version number over any other type of tag
tag_prefix = "v"

# Only releases from master are allowed
branch_whitelist = ["master"]

# Check commit history, starting from the latest tag to HEAD
from_latest_tag = true

pre_bump_hooks = [
  # Ensure our git identity is setup inside the gha runner
  "git config --global user.name github-actions[bot]",
  "git config --global user.email github-actions[bot]@users.noreply.github.com",

  # Run the package task to generate all the final artifacts
  "task package VERSION={{version}}",
]

post_bump_hooks = [
  # Publish artifacts, push up the changelogs & tags
  "task publish VERSION={{version}}",
]

# Create a CHANGELOG that includes helpful links to github diffs / commits / PRs, etc.
[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "brad-jones"
repository = "dotnetup"
authors = [
  { signature = "Brad Jones", username = "brad-jones" },
]
