# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: "3"

tasks:
  onCreate:
    desc: Connected to the devcontainer onCreateCommand hook
    cmds:
      - lefthook install -f
      - git config pull.rebase true
      - git config core.editor "code --wait"
      - git config commit.template "$PWD/.gitmsgtpl"
      - dotnet tool restore
      - dotnet restore

  fmt:
    desc: Runs dprint & dotnet format in fix mode
    cmds:
      - dprint fmt
      - dotnet format style -v d
      - dotnet format analyzers -v d

  lint:
    desc: Runs cog, dprint & dotnet format in check mode
    cmds:
      - cog check
      - dprint check
      - dotnet format style -v d --verify-no-changes
      - dotnet format analyzers -v d --verify-no-changes

  run:
    desc: Use me to quickly perform some manual exploratory testing / debugging.
    cmd: DOTNET_ROOT="./tmp-dn-root" dotnet run -p ./src/dotnetup.csproj -- {{.CLI_ARGS}}

  clean:
    desc: Deletes all generated files
    cmds:
      - rm -rf ./bin ./**/bin ./**/obj
      - dotnet restore

  build:
    desc: Builds both an AOT & Self-Contained binaries for the current host os
    vars:
      NEXT_VERSION:
        sh: cog bump -d -a | sed '1s/^.//' || echo "0.0.0"
    cmds:
      - dotnet publish ./src/dotnetup.csproj -c Release -o ./bin/x64-aot -a x64 -p:PublishProfile=Aot -p:Version={{.NEXT_VERSION}}
      - dotnet publish ./src/dotnetup.csproj -c Release -o ./bin/x64-sc -a x64 -p:PublishProfile=SelfContained -p:Version={{.NEXT_VERSION}}
      - dotnet publish ./src/dotnetup.csproj -c Release -o ./bin/arm64-sc -a arm64 -p:PublishProfile=SelfContained -p:Version={{.NEXT_VERSION}}
      - rm -rf ./bin/*/dotnetup.dbg ./bin/*/dotnetup.dsym ./bin/*/dotnetup.pdb || true
      - ls -hal ./bin/x64-aot ./bin/x64-sc ./bin/arm64-sc

  test:
    desc: Builds & then runs an end to end test suite on the built binaries (those that are native to the current host)
    deps:
      - build
    cmd: dotnet test ./test

  publish:
    desc: This is triggered by cog if there is a need to perform a release & generates the final publishable artifacts
    cmds:
      - mkdir -p ./publish
      - task: gzip-bins
      - task: stage-gzipped-bins
      - task: generate-digests

  gzip-bins:
    cmds:
      - gzip -k ./bin/linux-x64-aot/dotnetup
      - gzip -k ./bin/linux-x64-sc/dotnetup
      - gzip -k ./bin/linux-arm64-sc/dotnetup
      - gzip -k ./bin/darwin-x64-aot/dotnetup
      - gzip -k ./bin/darwin-x64-sc/dotnetup
      - gzip -k ./bin/darwin-arm64-sc/dotnetup
      - gzip -k ./bin/windows-x64-aot/dotnetup.exe
      - gzip -k ./bin/windows-x64-sc/dotnetup.exe
      - gzip -k ./bin/windows-arm64-sc/dotnetup.exe

  stage-gzipped-bins:
    cmds:
      - mv ./bin/linux-x64-aot/dotnetup.gz ./publish/dotnetup-linux-x64-aot.gz
      - mv ./bin/linux-x64-sc/dotnetup.gz ./publish/dotnetup-linux-x64-sc.gz
      - mv ./bin/linux-arm64-sc/dotnetup.gz ./publish/dotnetup-linux-arm64-sc.gz
      - mv ./bin/darwin-x64-aot/dotnetup.gz ./publish/dotnetup-darwin-x64-aot.gz
      - mv ./bin/darwin-x64-sc/dotnetup.gz ./publish/dotnetup-darwin-x64-sc.gz
      - mv ./bin/darwin-arm64-sc/dotnetup.gz ./publish/dotnetup-darwin-arm64-sc.gz
      - mv ./bin/windows-x64-aot/dotnetup.exe.gz ./publish/dotnetup-windows-x64-aot.exe.gz
      - mv ./bin/windows-x64-sc/dotnetup.exe.gz ./publish/dotnetup-windows-x64-sc.exe.gz
      - mv ./bin/windows-arm64-sc/dotnetup.exe.gz ./publish/dotnetup-windows-arm64-sc.exe.gz

  generate-digests:
    dir: ./publish
    cmd: sha256sum * > dotnetup-checksums.txt
