name: setup-deps
description: Install all project build dependencies
runs:
  using: "composite"
  steps:
    - name: Setup task
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: go-task/task
        tag: v3.33.1

    - name: Setup shfmt
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: mvdan/sh
        tag: v3.7.0
        extension-matching: disable
        rename-to: shfmt
        chmod: 0755

    - name: Setup dprint
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: dprint/dprint
        tag: 0.45.0

    - name: Setup cocogitto
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      if: runner.os == 'Linux'
      with:
        repo: cocogitto/cocogitto
        tag: 6.0.1
        binaries-location: x86_64-unknown-linux-musl

    - name: Setup cocogitto
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      if: runner.os == 'macOS'
      with:
        repo: cocogitto/cocogitto
        tag: 6.0.1
        binaries-location: x86_64-apple-darwin

    - name: Setup cocogitto
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      if: runner.os == 'Windows'
      with:
        repo: cocogitto/cocogitto
        tag: 6.0.1
        binaries-location: x86_64-pc-windows-msvc

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json

    - name: Setup dotnet tools
      run: dotnet tool restore
      shell: sh
