name: setup-deps
description: Install all project build dependencies
runs:
  using: "composite"
  steps:
    - name: Install dotnet
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json

    - name: Install pixi env
      uses: prefix-dev/setup-pixi@v0.9.0
      with:
        pixi-version: v0.55.0
        activate-environment: true

    - name: Install dotnet tools
      run: dotnet tool restore
      shell: sh
