on: { push: { branches: [master] } }

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oknozor/cocogitto-action@v3
      - uses: arduino/setup-task@v1
      - uses: mfinelli/setup-shfmt@v3
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json
      - run: dotnet tool restore
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "dprint/dprint"
          fileName: "dprint-x86_64-unknown-linux-gnu.zip"
          tag: "0.45.0"
          extract: true
          out-file-path: "./.tools"
      - run: chmod +x ./.tools/dprint && echo "$PWD/.tools" >> $GITHUB_PATH
      - run: task lint

  build_test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            os: linux
          - runner: windows-latest
            os: windows
          - runner: macos-latest
            os: darwin
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v1
      - uses: actions/setup-dotnet@v4
        with: { global-json-file: ./global.json }
      - run: task test
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-x64-aot
          path: bin/x64-aot/*
          compression-level: 0
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-arm64-sc
          path: bin/arm64-sc/*
          compression-level: 0
          if-no-files-found: error
