on: { push: { branches: [master] } }

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: ./.github/actions/setup-deps
      - run: task lint

  build_test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            os: linux
          - runner: windows-latest
            os: windows
          - runner: macos-latest
            os: darwin
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: ./.github/actions/setup-deps
      - run: task test
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-x64-aot
          path: bin/x64-aot/*
          compression-level: 0
          if-no-files-found: error
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-x64-sc
          path: bin/x64-sc/*
          compression-level: 0
          if-no-files-found: error
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-arm64-sc
          path: bin/arm64-sc/*
          compression-level: 0
          if-no-files-found: error
          retention-days: 1

  publish:
    needs: [lint, build_test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/download-artifact@v4
        with: { path: ./bin }
      - uses: ./.github/actions/setup-deps
      - run: cog bump --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
